# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\tnotebooks\"\xd8\x01\n\x07\x46\x65\x61ture\x12\x0b\n\x01s\x18\x01 \x01(\x0cH\x00\x12\x0b\n\x01\x66\x18\x02 \x01(\x02H\x00\x12\x0b\n\x01i\x18\x03 \x01(\x03H\x00\x12.\n\x0c\x66\x65\x61ture_list\x18\x04 \x01(\x0b\x32\x16.notebooks.FeatureListH\x00\x12,\n\x0b\x66\x65\x61ture_map\x18\x05 \x01(\x0b\x32\x15.notebooks.FeatureMapH\x00\"@\n\x0b\x46\x65\x61tureType\x12\r\n\tUNDEFINED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\x0b\n\x07\x46LOAT32\x10\x02\x12\t\n\x05INT64\x10\x03\x42\x06\n\x04kind\"4\n\x0b\x46\x65\x61tureList\x12%\n\tcontainer\x18\x01 \x03(\x0b\x32\x12.notebooks.Feature\"\x8b\x01\n\nFeatureMap\x12\x37\n\tcontainer\x18\x01 \x03(\x0b\x32$.notebooks.FeatureMap.ContainerEntry\x1a\x44\n\x0e\x43ontainerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.notebooks.Feature:\x02\x38\x01\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_FEATUREMAP_CONTAINERENTRY']._options = None
  _globals['_FEATUREMAP_CONTAINERENTRY']._serialized_options = b'8\001'
  _globals['_FEATURE']._serialized_start=28
  _globals['_FEATURE']._serialized_end=244
  _globals['_FEATURE_FEATURETYPE']._serialized_start=172
  _globals['_FEATURE_FEATURETYPE']._serialized_end=236
  _globals['_FEATURELIST']._serialized_start=246
  _globals['_FEATURELIST']._serialized_end=298
  _globals['_FEATUREMAP']._serialized_start=301
  _globals['_FEATUREMAP']._serialized_end=440
  _globals['_FEATUREMAP_CONTAINERENTRY']._serialized_start=372
  _globals['_FEATUREMAP_CONTAINERENTRY']._serialized_end=440
# @@protoc_insertion_point(module_scope)
